# /etc/stunnel/stunnel.conf
# Wraps RTMPS connections for Facebook and TikTok

[facebook-rtmp]
client  = yes
accept  = 127.0.0.1:19350
connect = live-api-s.facebook.com:443

[tiktok-rtmp]
client  = yes
accept  = 127.0.0.1:19351
connect = push-rtmp-f5-tt01.tiktokcdn-us.com:443
