<?php
session_start();
if (empty($_SESSION['authenticated'])) { http_response_code(401); exit; }
header('Content-Type: application/json');
require_once 'db.php';

$body = json_decode(file_get_contents('php://input'), true);
if (!$body) { echo json_encode(['success' => false, 'error' => 'Bad request']); exit; }

function sanitizeKey(mixed $v): string {
    return substr(preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)($v ?? '')), 0, 128);
}

$keyYt     = sanitizeKey($body['keys']['youtube']  ?? '');
$keyFb     = sanitizeKey($body['keys']['facebook'] ?? '');
$keyTt     = sanitizeKey($body['keys']['tiktok']   ?? '');
$ingestKey = sanitizeKey($body['ingest_key']       ?? '');
$enYt      = !empty($body['enabled']['youtube']);
$enFb      = !empty($body['enabled']['facebook']);
$enTt      = !empty($body['enabled']['tiktok']);
$restream  = !empty($body['restream']);

if (empty($ingestKey)) {
    echo json_encode(['success' => false, 'error' => 'Ingest key cannot be empty']);
    exit;
}

$db = new UmbraDB();
$db->set('key_youtube',      $keyYt);
$db->set('key_facebook',     $keyFb);
$db->set('key_tiktok',       $keyTt);
$db->set('ingest_key',       $ingestKey);
$db->set('enabled_youtube',  $enYt  ? '1' : '0');
$db->set('enabled_facebook', $enFb  ? '1' : '0');
$db->set('enabled_tiktok',   $enTt  ? '1' : '0');
$db->set('restream',         $restream ? '1' : '0');

// Build push lines
// Facebook: stunnel on 127.0.0.1:19350 → live-api-s.facebook.com:443
// TikTok:   stunnel on 127.0.0.1:19351 → push-rtmp-f5-tt01.tiktokcdn-us.com:443
$pushLines = '';
if ($restream) {
    if ($enYt && $keyYt) $pushLines .= "      push rtmp://a.rtmp.youtube.com/live2/{$keyYt};\n";
    if ($enFb && $keyFb) $pushLines .= "      push rtmp://127.0.0.1:19350/rtmp/{$keyFb};\n";
    if ($enTt && $keyTt) $pushLines .= "      push rtmp://127.0.0.1:19351/game/{$keyTt};\n";
}

$confPath = '/var/lib/umbra/rtmp_pushes.conf';
$written  = file_put_contents($confPath, "# Generated by Umbra\n{$pushLines}");

if ($written === false) {
    echo json_encode(['success' => false, 'error' => 'Failed to write ' . $confPath . ' — check ownership (should be www-data)']);
    exit;
}

$output = [];
$return = 0;
exec('sudo /usr/local/bin/umbra-reload 2>&1', $output, $return);

if ($return !== 0) {
    echo json_encode(['success' => false, 'error' => 'nginx reload failed: ' . implode(' ', $output)]);
    exit;
}

echo json_encode(['success' => true]);
