<?php
session_start();
if (empty($_SESSION['authenticated'])) { http_response_code(401); exit; }
header('Content-Type: application/json');
require_once 'db.php';

$body = json_decode(file_get_contents('php://input'), true);
if (!$body) { echo json_encode(['success' => false, 'error' => 'Bad request']); exit; }

function sanitizeKey(mixed $v, int $max = 128): string {
    return substr(preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)($v ?? '')), 0, $max);
}
function sanitizeUrl(mixed $v): string {
    $url = trim((string)($v ?? ''));
    // Allow rtmp:// urls with slashes, dots, colons, alphanumeric
    return preg_match('#^rtmps?://[a-zA-Z0-9\.\-/:_]+$#', $url) ? $url : '';
}
function sanitizeHost(mixed $v): string {
    $h = trim((string)($v ?? ''));
    // hostname:port format
    return preg_match('#^[a-zA-Z0-9\.\-]+:\d+$#', $h) ? $h : '';
}

$keyYt          = sanitizeKey($body['keys']['youtube']       ?? '');
$keyFb          = sanitizeKey($body['keys']['facebook']      ?? '');
$keyTt          = sanitizeKey($body['keys']['tiktok']        ?? '');
$ingestKey      = sanitizeKey($body['ingest_key']            ?? '', 64);
$enYt           = !empty($body['enabled']['youtube']);
$enFb           = !empty($body['enabled']['facebook']);
$enTt           = !empty($body['enabled']['tiktok']);
$restream       = !empty($body['restream']);
$urlYt          = sanitizeUrl($body['urls']['youtube']       ?? '');
$urlFb          = sanitizeUrl($body['urls']['facebook']      ?? '');
$urlTt          = sanitizeUrl($body['urls']['tiktok']        ?? '');
$stunnelFb      = sanitizeHost($body['stunnel']['facebook']  ?? '');
$stunnelTt      = sanitizeHost($body['stunnel']['tiktok']    ?? '');

// Validate required fields
$errors = [];
if (empty($ingestKey))  $errors[] = 'Ingest key cannot be empty';
if (empty($urlYt))      $errors[] = 'YouTube push URL is invalid';
if (empty($urlFb))      $errors[] = 'Facebook push URL is invalid';
if (empty($urlTt))      $errors[] = 'TikTok push URL is invalid';
if (empty($stunnelFb))  $errors[] = 'Facebook stunnel host is invalid (use hostname:port)';
if (empty($stunnelTt))  $errors[] = 'TikTok stunnel host is invalid (use hostname:port)';
if ($errors) { echo json_encode(['success' => false, 'error' => implode('. ', $errors)]); exit; }

// Save to DB
$db = new UmbraDB();
$db->set('key_youtube',      $keyYt);
$db->set('key_facebook',     $keyFb);
$db->set('key_tiktok',       $keyTt);
$db->set('ingest_key',       $ingestKey);
$db->set('enabled_youtube',  $enYt  ? '1' : '0');
$db->set('enabled_facebook', $enFb  ? '1' : '0');
$db->set('enabled_tiktok',   $enTt  ? '1' : '0');
$db->set('restream',         $restream ? '1' : '0');
$db->set('url_youtube',      $urlYt);
$db->set('url_facebook',     $urlFb);
$db->set('url_tiktok',       $urlTt);
$db->set('stunnel_facebook',  $stunnelFb);
$db->set('stunnel_tiktok',    $stunnelTt);

// Write rtmp_pushes.conf
$pushLines = '';
if ($restream) {
    if ($enYt && $keyYt) $pushLines .= "      push {$urlYt}/{$keyYt};\n";
    if ($enFb && $keyFb) $pushLines .= "      push {$urlFb}/{$keyFb};\n";
    if ($enTt && $keyTt) $pushLines .= "      push {$urlTt}/{$keyTt};\n";
}
$written = file_put_contents('/var/lib/umbra/rtmp_pushes.conf', "# Generated by Umbra\n{$pushLines}");
if ($written === false) {
    echo json_encode(['success' => false, 'error' => 'Failed to write rtmp_pushes.conf — check ownership of /var/lib/umbra']);
    exit;
}

// Write stunnel.conf
$stunnelConf = "[facebook-rtmp]\nclient = yes\naccept = 127.0.0.1:19350\nconnect = {$stunnelFb}\n\n[tiktok-rtmp]\nclient = yes\naccept = 127.0.0.1:19351\nconnect = {$stunnelTt}\n";
$written = file_put_contents('/var/lib/umbra/stunnel.conf', $stunnelConf);
if ($written === false) {
    echo json_encode(['success' => false, 'error' => 'Failed to write stunnel config']);
    exit;
}

// Reload via privileged script
$output = [];
$return = 0;
exec('sudo /usr/local/bin/umbra-reload 2>&1', $output, $return);
if ($return !== 0) {
    echo json_encode(['success' => false, 'error' => 'Reload failed: ' . implode(' ', $output)]);
    exit;
}

echo json_encode(['success' => true]);
