<?php
session_start();
if (empty($_SESSION['authenticated'])) { http_response_code(401); exit; }

header('Content-Type: application/json');
require_once 'db.php';

$body = json_decode(file_get_contents('php://input'), true);
if (!$body) { echo json_encode(['success' => false, 'error' => 'Bad request']); exit; }

// Sanitize platform stream keys — alphanumeric, hyphens, underscores only
function sanitizeStreamKey(mixed $v): string {
    return preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)($v ?? ''));
}

// Ingest key: allow alphanumeric + hyphens + underscores, max 64 chars
function sanitizeIngestKey(mixed $v): string {
    $clean = preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)($v ?? ''));
    return substr($clean, 0, 64);
}

$keyYt     = sanitizeStreamKey($body['keys']['youtube']  ?? '');
$keyFb     = sanitizeStreamKey($body['keys']['facebook'] ?? '');
$keyTt     = sanitizeStreamKey($body['keys']['tiktok']   ?? '');
$ingestKey = sanitizeIngestKey($body['ingest_key']       ?? '');
$enYt      = !empty($body['enabled']['youtube']);
$enFb      = !empty($body['enabled']['facebook']);
$enTt      = !empty($body['enabled']['tiktok']);
$restream  = !empty($body['restream']);

// Refuse to save an empty ingest key — that would leave the port wide open
if (empty($ingestKey)) {
    echo json_encode(['success' => false, 'error' => 'Ingest key cannot be empty']);
    exit;
}

// Save everything to DB
$db = new UmbraDB();
$db->set('key_youtube',      $keyYt);
$db->set('key_facebook',     $keyFb);
$db->set('key_tiktok',       $keyTt);
$db->set('ingest_key',       $ingestKey);
$db->set('enabled_youtube',  $enYt  ? '1' : '0');
$db->set('enabled_facebook', $enFb  ? '1' : '0');
$db->set('enabled_tiktok',   $enTt  ? '1' : '0');
$db->set('restream',         $restream ? '1' : '0');

// Write platform push lines for nginx include
@mkdir('/etc/umbra', 0750, true);
$pushLines = '';
if ($restream) {
    if ($enYt && $keyYt) $pushLines .= "      push rtmp://a.rtmp.youtube.com/live2/{$keyYt};\n";
    if ($enFb && $keyFb) $pushLines .= "      push rtmp://127.0.0.1:19350/rtmp/{$keyFb};\n";
    if ($enTt && $keyTt) $pushLines .= "      push rtmp://push.tiktok.com/live/{$keyTt};\n";
}

$conf = "# Generated by Umbra — do not edit manually\n{$pushLines}";
file_put_contents('/etc/umbra/rtmp_pushes.conf', $conf);

// Reload nginx + stunnel via privileged wrapper
$output = [];
$return = 0;
exec('sudo /usr/local/bin/umbra-reload 2>&1', $output, $return);

if ($return !== 0) {
    echo json_encode([
        'success' => false,
        'error'   => 'nginx reload failed: ' . implode(' ', $output),
    ]);
    exit;
}

echo json_encode(['success' => true]);
